backend:
  name: github
  repo: tsikyfockso-ctrl/Novatour-Agency  # ton GitHub username + repo
  branch: main
  auth_scope: repo

media_folder: "images"      # dossier pour stocker les images
public_folder: "/images"    # chemin utilis√© dans ton site HTML

collections:
  - name: "pages"
    label: "Pages"
    folder: ""              # racine pour les fichiers HTML
    create: false
    files:
      - file: "index.html"
        label: "Page d'accueil"
        name: "home"
        fields:
          - { label: "Contenu HTML", name: "body", widget: "markdown" }
