backend:
  name: github
  repo: tsikyfockso-ctrl/novatouragency  # ton GitHub username + repo
  branch: main
  auth_scope: repo

media_folder:      # Racine du dépôt
public_folder: "./"    # chemin utilisé dans mon site HTML

collections:
  - name: "pages"
    label: "Pages"
    folder: "./"              # racine pour les fichiers HTML
    create: false
    files:
      - file: "index.html"
        label: "Page d'accueil"
        name: "home"
        fields:
          - { label: "Contenu HTML", name: "body", widget: "markdown" }
